- arguments: [
  -XQuasiQuotes,
  -XFunctionalDependencies,
  -XLambdaCase,
  -XLambdaCase,
  -XOverloadedStrings,
  -XQuasiQuotes,
  -XTemplateHaskell,
  -XTupleSections,
  -XTypeFamilies,
  -XViewPatterns
  ]

- group: {name: future, enabled: true}
- group: {name: extra, enabled: true}
- group: {name: use-lens, enabled: true}
- group: {name: dollar, enabled: true}
